ALTER TYPE appraisal_stage ADD VALUE IF NOT EXISTS 'CALIBRATION' AFTER 'CEO_REVIEW';
ALTER TYPE appraisal_stage ADD VALUE IF NOT EXISTS 'PROMOTION_REVIEW' AFTER 'COMPENSATION_REVIEW';
ALTER TYPE appraisal_stage ADD VALUE IF NOT EXISTS 'DISCUSSION' AFTER 'FINAL_APPROVAL';

ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS calibrated_rating DECIMAL(4,2);
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS hr_calibration_notes TEXT;
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS proposed_salary DECIMAL(14,2);
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS salary_increment_pct DECIMAL(5,2);
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS promotion_recommended BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS proposed_designation TEXT;
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS appraisal_letter_url TEXT;
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS discussion_scheduled_at TIMESTAMP;
ALTER TABLE appraisals ADD COLUMN IF NOT EXISTS discussion_notes TEXT;
